# Autogenerated by devscripts/update-version.py

__version__ = '2023.12.13.120820'

RELEASE_GIT_HEAD = 'ae953a1f41cf3616008aa65706a5e4e1a45ff3cf'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
