# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.02.215052'

RELEASE_GIT_HEAD = '8a2585400c70ff3ecde94d669de2d618c67cf0ad'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'denizkoekden/yt-dlp_sinusbot'

ORIGIN = 'denizkoekden/yt-dlp_sinusbot'

_pkg_version = '2024.01.02.215052'
