# Autogenerated by devscripts/update-version.py

__version__ = '2024.07.23.111800'

RELEASE_GIT_HEAD = '23fc1167b3510942e10e1145ff1f6ef51f7bb22a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'denizkoekden/yt-dlp_sinusbot'

ORIGIN = 'denizkoekden/yt-dlp_sinusbot'

_pkg_version = '2024.07.23.111800'
